<?php

/**
 * Implements hook_preprocess().
 */
function heymp_theme_hacks_preprocess_entity(&$variables, $hook) {
  $entity_type = $variables['elements']['#entity_type'];

  foreach($variables['theme_hook_suggestions'] as &$suggestion) {
    $suggestion = 'entity__' . $suggestion;
  }

  if ($entity_type) {
    $function = 'heymp_theme_hacks_preprocess_entity_' . $entity_type;
    if (function_exists($function)) {
      $function($variables);
    }
  }
}