<?php

/**
 * Implements hook_preprocess_entity().
 */
function heymp_theme_hacks_preprocess_entity(&$variables, $hook) {
  $entity_type = $variables['elements']['#entity_type'];

  foreach($variables['theme_hook_suggestions'] as &$suggestion) {
    $suggestion = 'entity__' . $suggestion;
  }

  if ($entity_type) {
    $function = 'heymp_theme_hacks_preprocess_entity_' . $entity_type;
    if (function_exists($function)) {
      $function($variables);
    }
  }
}

/**
 * Implements hook_preprocess().
 *
 * Example of how to add svg's into your theme:
 * <svg class="svg-sample featurelist__icon" viewBox="0 0 288 176.6">
 *   <use xlink:href="<?php print $svg_sprite_path; ?>#email"></use>
 * </svg>
 */
// function heymp_theme_hacks_preprocess(&$variables) {
//   $theme_path = path_to_theme();
//   $variables['theme_path'] = $base_url . '/' . $theme_path;
//   $variables['svg_sprite_path'] = $base_url . '/' . $theme_path . '/frontend-dev/svg/dist/symbol/svg/sprite.symbol.svg';
//   $variables['svg_sprite'] = file_get_contents($theme_path . '/frontend-dev/svg/dist/symbol/svg/sprite.symbol.svg');
// }

/**
 * Helper function to remove unique multidimensional arrays
 */
function _heymp_theme_hacks_array_unique_recursive($array) {
  $result = array_map("unserialize", array_unique(array_map("serialize", $array)));

  foreach ($result as $key => $value)
  {
    if ( is_array($value) )
    {
      $result[$key] = super_unique($value);
    }
  }

  return $result;
}
